### ISSUE TITLE
what do 'n.v' & 'n.a' POS denote?

### ISSUE THREAD

**Issue by rickysahu** [Mchristos/lexsub#1]
The library supports these POS
` self.poses = ['n', 'a', 'r', 'n.v', 'v', 'n.a'] # ['n'] `
Which POS in NLTK do `n.v` & `n.a` map to?

**Comment by Mchristos** [comment]
That is a very good question. When I was working on this problem, I was working against a gold standard file which annotated words in context with their POS, and that's where these came from. I actually have no idea what they refer to - I think I assumed they referred to something and that I would support them later on. In practice these POSes are just used to generate synonyms, and you're right that they don't correspond to anything in NLTK as far as I can tell - so I will remove them. Thanks for picking this up!

**Comment by Mchristos** [comment]
That's a very good question...
